In [1]:
import pandas as pd

df = pd.read_csv('aice_associate_customer_churn.csv')

In [2]:
df.head()

,customer_id,gender,age,city,signup_date,plan_type,payment_method,monthly_usage_hours,support_calls,monthly_fee,satisfaction_score,churn
0,C0001,F,42.0,Busan,2025-07-12,Standard,Bank,43.4,3,34.8,1,1
1,C0002,F,31.0,Seoul,2024-01-07,Standard,Card,25.3,2,33.6,3,0
2,C0003,F,38.0,Incheon,2025-04-15,Standard,Mobile,44.7,0,27.8,3,0
3,C0004,M,21.0,Busan,2024-03-22,Basic,Card,20.0,4,15.0,3,1
4,C0005,M,36.0,Incheon,2024-06-24,Standard,Bank,50.4,0,33.0,3,0

In [3]:
df.shape

(220, 12)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          220 non-null    str
 1   gender               220 non-null    str
 2   age                  208 non-null    float64
 3   city                 211 non-null    str
 4   signup_date          220 non-null    str
 5   plan_type            220 non-null    str
 6   payment_method       220 non-null    str
 7   monthly_usage_hours  213 non-null    float64
 8   support_calls        220 non-null    int64
 9   monthly_fee          220 non-null    float64
 10  satisfaction_score   220 non-null    int64
 11  churn                220 non-null    int64
dtypes: float64(3), int64(3), str(6)
memory usage: 20.8 KB

In [11]:
df['age'].isnull().sum()

np.int64(12)

In [9]:
df.dtypes

customer_id                str
gender                     str
age                    float64
city                       str
signup_date                str
plan_type                  str
payment_method             str
monthly_usage_hours    float64
support_calls            int64
monthly_fee            float64
satisfaction_score       int64
churn                    int64
dtype: object

In [12]:
df['city'].isnull().sum()

np.int64(9)

In [13]:
df.describe()

,age,monthly_usage_hours,support_calls,monthly_fee,satisfaction_score,churn
count,208.000000,213.000000,220.000000,220.000000,220.000000,220.000000
mean,34.168269,39.079812,1.922727,30.374091,3.336364,0.263636
std,10.466674,17.312822,1.555204,13.559570,1.203323,0.441609
min,19.000000,4.700000,0.000000,13.400000,1.000000,0.000000
25%,27.000000,26.900000,1.000000,18.800000,3.000000,0.000000
50%,34.000000,38.000000,2.000000,29.600000,3.000000,0.000000
75%,40.250000,49.000000,3.000000,35.975000,4.000000,1.000000
max,101.000000,145.700000,6.000000,63.900000,5.000000,1.000000

In [14]:
df['city'].value_counts()

city
Seoul      86
Busan      58
Incheon    38
Daegu      29
Name: count, dtype: int64

In [15]:
df['plan_type'].value_counts()

plan_type
Basic       100
Standard     81
Premium      39
Name: count, dtype: int64

In [16]:
df['age'] >= 30

0       True
1       True
2       True
3      False
4       True
       ...
215    False
216     True
217    False
218    False
219     True
Name: age, Length: 220, dtype: bool

In [17]:
df[df['age'] >= 30]

,customer_id,gender,age,city,signup_date,plan_type,payment_method,monthly_usage_hours,support_calls,monthly_fee,satisfaction_score,churn
0,C0001,F,42.0,Busan,2025-07-12,Standard,Bank,43.4,3,34.8,1,1
1,C0002,F,31.0,Seoul,2024-01-07,Standard,Card,25.3,2,33.6,3,0
2,C0003,F,38.0,Incheon,2025-04-15,Standard,Mobile,44.7,0,27.8,3,0
4,C0005,M,36.0,Incheon,2024-06-24,Standard,Bank,50.4,0,33.0,3,0
7,C0008,F,30.0,Busan,2025-11-27,Basic,Bank,27.7,1,19.4,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...
210,C0211,F,33.0,Incheon,2024-09-22,Standard,Bank,35.7,2,33.1,4,0
212,C0213,M,38.0,Seoul,2024-01-03,Basic,Bank,4.9,5,20.4,3,1
214,C0215,F,42.0,Incheon,2025-04-21,Premium,Card,75.9,4,56.9,3,0
216,C0217,M,47.0,Seoul,2024-12-09,Standard,Card,44.1,4,33.8,5,0
219,C0220,M,31.0,NaN,2025-08-21,Basic,Bank,36.0,2,19.7,3,0

In [18]:
df[df['monthly_fee'] >= 30]

,customer_id,gender,age,city,signup_date,plan_type,payment_method,monthly_usage_hours,support_calls,monthly_fee,satisfaction_score,churn
0,C0001,F,42.0,Busan,2025-07-12,Standard,Bank,43.4,3,34.8,1,1
1,C0002,F,31.0,Seoul,2024-01-07,Standard,Card,25.3,2,33.6,3,0
4,C0005,M,36.0,Incheon,2024-06-24,Standard,Bank,50.4,0,33.0,3,0
8,C0009,F,32.0,Incheon,2024-12-14,Standard,Bank,37.1,3,40.9,3,0
9,C0010,F,30.0,Seoul,2024-07-22,Premium,Bank,57.7,3,48.0,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...
200,C0201,M,39.0,Busan,2024-10-07,Standard,Card,58.1,3,31.4,2,1
205,C0206,F,43.0,Busan,2025-02-05,Standard,Bank,28.8,2,37.9,5,1
210,C0211,F,33.0,Incheon,2024-09-22,Standard,Bank,35.7,2,33.1,4,0
214,C0215,F,42.0,Incheon,2025-04-21,Premium,Card,75.9,4,56.9,3,0
216,C0217,M,47.0,Seoul,2024-12-09,Standard,Card,44.1,4,33.8,5,0

In [19]:
df[(df['age'] >= 30) & (df['support_calls'] >= 3)]

,customer_id,gender,age,city,signup_date,plan_type,payment_method,monthly_usage_hours,support_calls,monthly_fee,satisfaction_score,churn
0,C0001,F,42.0,Busan,2025-07-12,Standard,Bank,43.4,3,34.8,1,1
8,C0009,F,32.0,Incheon,2024-12-14,Standard,Bank,37.1,3,40.9,3,0
9,C0010,F,30.0,Seoul,2024-07-22,Premium,Bank,57.7,3,48.0,4,1
10,C0011,M,30.0,NaN,2024-09-02,Premium,Mobile,58.4,5,57.0,5,1
11,C0012,F,42.0,Seoul,2025-03-09,Basic,Mobile,37.0,6,17.7,4,0
16,C0017,F,52.0,Busan,2025-02-14,Standard,Card,32.5,3,27.8,1,0
19,C0020,F,32.0,Busan,2024-11-19,Standard,Bank,40.5,3,34.2,4,0
28,C0029,M,39.0,Incheon,2024-09-28,Basic,Mobile,26.0,4,19.8,3,0
38,C0039,M,35.0,Incheon,2025-07-13,Basic,Bank,6.4,3,13.9,3,0
42,C0043,M,35.0,Seoul,2024-06-16,Standard,Card,35.4,3,32.0,1,0
63,C0064,M,38.0,Busan,2025-05-16,Standard,Mobile,NaN,3,31.1,3,0
64,C0065,M,54.0,Busan,2025-02-24,Basic,Mobile,5.4,5,20.1,4,0
65,C0066,F,32.0,Seoul,2025-03-26,Standard,Mobile,42.1,5,38.4,1,0
71,C0072,M,53.0,Seoul,2024-02-20,Basic,Mobile,30.8,4,16.8,5,1
72,C0073,M,36.0,Busan,2025-11-28,Standard,Bank,49.0,3,32.2,5,0
73,C0074,M,34.0,Busan,2024-05-15,Standard,Card,37.2,3,31.2,3,1
74,C0075,M,43.0,Incheon,2024-03-18,Premium,Card,56.1,5,40.2,5,0
89,C0090,M,43.0,Busan,2024-03-12,Basic,Bank,23.2,3,21.8,1,1
90,C0091,M,39.0,Seoul,2024-02-23,Premium,Bank,65.9,3,56.7,1,0
92,C0093,F,41.0,Daegu,2024-05-02,Standard,Card,67.4,5,30.0,2,1
95,C0096,M,38.0,Busan,2024-07-17,Standard,Bank,60.8,3,36.7,4,0
102,C0103,M,40.0,Daegu,2025-06-23,Standard,Bank,26.9,4,37.0,4,0
107,C0108,F,35.0,Incheon,2024-08-15,Basic,Card,19.2,3,14.3,5,0
109,C0110,M,34.0,Busan,2025-07-15,Basic,Mobile,28.4,4,17.7,3,1
111,C0112,M,35.0,Seoul,2024-03-10,Basic,Mobile,39.4,4,18.1,4,0
116,C0117,F,34.0,Seoul,2024-11-24,Premium,Bank,53.6,3,56.7,3,1
129,C0130,F,32.0,Seoul,2024-06-12,Basic,Mobile,38.5,3,13.6,4,0
143,C0144,M,34.0,Daegu,2024-02-08,Standard,Card,45.7,3,37.5,5,0
144,C0145,M,36.0,Daegu,2024-02-08,Premium,Card,51.1,4,53.6,2,0
145,C0146,M,39.0,Seoul,2024-12-04,Basic,Mobile,24.2,3,21.4,3,0
150,C0151,F,45.0,Seoul,2025-05-15,Standard,Bank,60.6,4,30.0,5,0
152,C0153,F,46.0,Busan,2025-10-18,Basic,Card,26.9,4,18.5,3,0
157,C0158,M,55.0,Seoul,2025-07-24,Basic,Card,5.5,5,17.4,5,0
166,C0167,M,48.0,Incheon,2024-01-17,Premium,Bank,63.8,4,53.3,1,0
172,C0173,M,35.0,Incheon,2024-12-20,Standard,Bank,36.0,4,30.8,5,0
174,C0175,M,39.0,Busan,2025-10-11,Basic,Bank,11.4,3,21.0,3,0
184,C0185,F,33.0,Busan,2024-04-28,Basic,Mobile,30.0,3,15.5,3,0
195,C0196,M,30.0,Incheon,2025-06-10,Basic,Bank,24.2,4,18.7,2,0
200,C0201,M,39.0,Busan,2024-10-07,Standard,Card,58.1,3,31.4,2,1
202,C0203,F,45.0,Busan,2024-04-14,Basic,Card,27.1,3,20.4,3,0
212,C0213,M,38.0,Seoul,2024-01-03,Basic,Bank,4.9,5,20.4,3,1
214,C0215,F,42.0,Incheon,2025-04-21,Premium,Card,75.9,4,56.9,3,0
216,C0217,M,47.0,Seoul,2024-12-09,Standard,Card,44.1,4,33.8,5,0

In [20]:
df[(df['plan_type'] == 'Premium') | (df['monthly_fee'] <= 2)]

,customer_id,gender,age,city,signup_date,plan_type,payment_method,monthly_usage_hours,support_calls,monthly_fee,satisfaction_score,churn
9,C0010,F,30.0,Seoul,2024-07-22,Premium,Bank,57.7,3,48.0,4,1
10,C0011,M,30.0,NaN,2024-09-02,Premium,Mobile,58.4,5,57.0,5,1
25,C0026,F,27.0,Incheon,2024-08-30,Premium,Bank,69.2,5,53.2,5,0
30,C0031,M,NaN,Busan,2025-11-13,Premium,Bank,46.7,0,57.7,3,0
35,C0036,M,22.0,Seoul,2024-06-11,Premium,Bank,46.6,2,61.1,3,0
39,C0040,M,31.0,Incheon,2025-02-07,Premium,Bank,37.2,0,58.4,2,1
41,C0042,F,37.0,Daegu,2024-01-21,Premium,Card,42.3,1,62.0,3,0
43,C0044,M,41.0,Seoul,2025-12-14,Premium,Card,55.4,2,63.9,4,0
49,C0050,F,33.0,Daegu,2024-07-15,Premium,Bank,48.6,2,53.1,4,0
55,C0056,F,23.0,NaN,2024-03-14,Premium,Mobile,64.3,5,43.9,4,0
59,C0060,M,34.0,Daegu,2024-01-02,Premium,Mobile,63.5,0,58.4,3,0
60,C0061,M,35.0,Seoul,2025-12-16,Premium,Card,50.6,1,46.5,4,0
61,C0062,F,30.0,Incheon,2024-04-30,Premium,Card,56.4,1,61.5,5,0
74,C0075,M,43.0,Incheon,2024-03-18,Premium,Card,56.1,5,40.2,5,0
76,C0077,M,41.0,Busan,2024-11-05,Premium,Mobile,54.0,1,57.8,1,1
79,C0080,M,30.0,Incheon,2024-08-05,Premium,Card,86.5,0,50.4,1,1
88,C0089,F,41.0,Incheon,2025-10-20,Premium,Bank,38.1,0,52.9,4,0
90,C0091,M,39.0,Seoul,2024-02-23,Premium,Bank,65.9,3,56.7,1,0
98,C0099,M,36.0,Incheon,2025-06-03,Premium,Bank,54.2,0,52.6,5,0
108,C0109,M,44.0,Busan,2025-10-27,Premium,Mobile,57.6,1,51.2,1,0
114,C0115,F,41.0,Busan,2025-07-10,Premium,Bank,60.0,1,63.7,4,1
116,C0117,F,34.0,Seoul,2024-11-24,Premium,Bank,53.6,3,56.7,3,1
120,C0121,F,34.0,Seoul,2025-05-17,Premium,Card,66.5,2,61.0,1,0
124,C0125,F,35.0,Seoul,2025-06-14,Premium,Mobile,52.3,2,49.5,3,0
127,C0128,M,29.0,Busan,2025-04-09,Premium,Card,50.7,2,54.3,3,0
130,C0131,M,26.0,Busan,2024-09-03,Premium,Bank,58.1,2,54.3,1,0
132,C0133,F,26.0,Seoul,2025-09-17,Premium,Bank,65.9,5,49.6,3,0
136,C0137,M,41.0,Seoul,2025-11-28,Premium,Card,71.6,2,59.0,4,0
137,C0138,M,31.0,Daegu,2024-03-04,Premium,Mobile,47.5,1,53.9,4,0
144,C0145,M,36.0,Daegu,2024-02-08,Premium,Card,51.1,4,53.6,2,0
146,C0147,F,43.0,Incheon,2024-03-29,Premium,Bank,77.3,1,55.7,5,1
159,C0160,F,42.0,Seoul,2024-05-17,Premium,Bank,35.1,1,56.6,3,0
165,C0166,F,19.0,Busan,2024-01-07,Premium,Card,54.8,0,53.3,3,0
166,C0167,M,48.0,Incheon,2024-01-17,Premium,Bank,63.8,4,53.3,1,0
167,C0168,F,19.0,Seoul,2024-04-08,Premium,Card,57.8,0,58.7,4,0
168,C0169,F,27.0,Seoul,2025-12-01,Premium,Card,66.0,2,53.0,5,0
182,C0183,M,19.0,Seoul,2025-10-15,Premium,Bank,NaN,2,51.4,3,0
194,C0195,F,39.0,Seoul,2025-03-14,Premium,Bank,75.4,2,55.7,2,1
214,C0215,F,42.0,Incheon,2025-04-21,Premium,Card,75.9,4,56.9,3,0

In [21]:
df[(df['plan_type'] == 'Premium')|(df['monthly_fee'] <= 20)]

,customer_id,gender,age,city,signup_date,plan_type,payment_method,monthly_usage_hours,support_calls,monthly_fee,satisfaction_score,churn
3,C0004,M,21.0,Busan,2024-03-22,Basic,Card,20.0,4,15.0,3,1
5,C0006,F,27.0,Daegu,2024-11-19,Basic,Card,8.6,1,19.5,5,1
6,C0007,M,19.0,Seoul,2025-07-28,Basic,Card,42.9,0,18.0,3,0
7,C0008,F,30.0,Busan,2025-11-27,Basic,Bank,27.7,1,19.4,3,0
9,C0010,F,30.0,Seoul,2024-07-22,Premium,Bank,57.7,3,48.0,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...
209,C0210,M,32.0,Busan,2025-04-09,Basic,Card,6.9,1,18.5,4,1
213,C0214,F,19.0,NaN,2025-03-02,Basic,Card,20.1,3,17.9,5,0
214,C0215,F,42.0,Incheon,2025-04-21,Premium,Card,75.9,4,56.9,3,0
217,C0218,F,19.0,Incheon,2024-02-14,Basic,Card,41.5,5,16.5,4,0
219,C0220,M,31.0,NaN,2025-08-21,Basic,Bank,36.0,2,19.7,3,0

In [22]:
df.sort_values('age')

,customer_id,gender,age,city,signup_date,plan_type,payment_method,monthly_usage_hours,support_calls,monthly_fee,satisfaction_score,churn
6,C0007,M,19.0,Seoul,2025-07-28,Basic,Card,42.9,0,18.0,3,0
24,C0025,F,19.0,Seoul,2024-11-11,Basic,Card,22.1,0,23.4,5,0
20,C0021,M,19.0,Incheon,2025-07-30,Basic,Bank,34.7,2,19.0,2,0
17,C0018,M,19.0,Incheon,2024-06-07,Standard,Bank,54.8,2,33.9,1,1
33,C0034,F,19.0,Seoul,2025-02-13,Standard,Card,48.3,2,34.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
118,C0119,F,NaN,Seoul,2024-03-09,Standard,Card,40.2,2,34.9,3,1
175,C0176,M,NaN,Seoul,2024-04-15,Standard,Bank,44.8,3,31.5,2,1
197,C0198,M,NaN,Daegu,2025-12-12,Basic,Bank,36.9,3,18.1,5,0
206,C0207,M,NaN,Incheon,2024-11-20,Basic,Card,24.8,4,22.7,4,0
218,C0219,F,NaN,Seoul,2024-03-04,Basic,Bank,21.7,0,21.6,3,0

In [23]:
df.sort_values('age', ascending=False)

,customer_id,gender,age,city,signup_date,plan_type,payment_method,monthly_usage_hours,support_calls,monthly_fee,satisfaction_score,churn
14,C0015,F,101.0,Seoul,2025-11-20,Standard,Bank,48.7,0,33.1,1,1
139,C0140,F,61.0,Daegu,2025-05-15,Standard,Bank,30.8,1,34.8,5,1
157,C0158,M,55.0,Seoul,2025-07-24,Basic,Card,5.5,5,17.4,5,0
83,C0084,F,54.0,Seoul,2025-03-30,Basic,Bank,NaN,2,19.5,4,0
64,C0065,M,54.0,Busan,2025-02-24,Basic,Mobile,5.4,5,20.1,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...
118,C0119,F,NaN,Seoul,2024-03-09,Standard,Card,40.2,2,34.9,3,1
175,C0176,M,NaN,Seoul,2024-04-15,Standard,Bank,44.8,3,31.5,2,1
197,C0198,M,NaN,Daegu,2025-12-12,Basic,Bank,36.9,3,18.1,5,0
206,C0207,M,NaN,Incheon,2024-11-20,Basic,Card,24.8,4,22.7,4,0
218,C0219,F,NaN,Seoul,2024-03-04,Basic,Bank,21.7,0,21.6,3,0

In [24]:
df.sort_values("age", ascending=False).iloc[0]

customer_id                 C0015
gender                          F
age                         101.0
city                        Seoul
signup_date            2025-11-20
plan_type                Standard
payment_method               Bank
monthly_usage_hours          48.7
support_calls                   0
monthly_fee                  33.1
satisfaction_score              1
churn                           1
Name: 14, dtype: object

In [25]:
df.sort_values("age").iloc[0]

customer_id                 C0007
gender                          M
age                          19.0
city                        Seoul
signup_date            2025-07-28
plan_type                   Basic
payment_method               Card
monthly_usage_hours          42.9
support_calls                   0
monthly_fee                  18.0
satisfaction_score              3
churn                           0
Name: 6, dtype: object

In [27]:
df.sort_values("age", ascending=False).iloc[0]["customer_id"]

'C0015'

In [28]:
df.sort_values("age").iloc[0]["customer_id"]

'C0007'

In [30]:
df.loc[df['age']>=30, ['customer_id','age']]

    customer_id   age
0         C0001  42.0
1         C0002  31.0
2         C0003  38.0
4         C0005  36.0
7         C0008  30.0
..          ...   ...
210       C0211  33.0
212       C0213  38.0
214       C0215  42.0
216       C0217  47.0
219       C0220  31.0

[141 rows x 2 columns]

In [31]:
df.groupby('plan_type')['monthly_fee'].mean()

plan_type
Basic       18.657000
Premium     54.787179
Standard    33.085185
Name: monthly_fee, dtype: float64

In [32]:
df.groupby('plan_type')['monthly_usage_hours'].max()

plan_type
Basic        56.7
Premium      86.5
Standard    145.7
Name: monthly_usage_hours, dtype: float64

In [33]:
df.groupby('city')['satisfaction_score'].mean()

city
Busan      3.120690
Daegu      3.827586
Incheon    3.368421
Seoul      3.313953
Name: satisfaction_score, dtype: float64

In [ ]:
df[df['age']>=30]

,customer_id,gender,age,city,signup_date,plan_type,payment_method,monthly_usage_hours,support_calls,monthly_fee,satisfaction_score,churn
0,C0001,F,42.0,Busan,2025-07-12,Standard,Bank,43.4,3,34.8,1,1
1,C0002,F,31.0,Seoul,2024-01-07,Standard,Card,25.3,2,33.6,3,0
2,C0003,F,38.0,Incheon,2025-04-15,Standard,Mobile,44.7,0,27.8,3,0
4,C0005,M,36.0,Incheon,2024-06-24,Standard,Bank,50.4,0,33.0,3,0
7,C0008,F,30.0,Busan,2025-11-27,Basic,Bank,27.7,1,19.4,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...
210,C0211,F,33.0,Incheon,2024-09-22,Standard,Bank,35.7,2,33.1,4,0
212,C0213,M,38.0,Seoul,2024-01-03,Basic,Bank,4.9,5,20.4,3,1
214,C0215,F,42.0,Incheon,2025-04-21,Premium,Card,75.9,4,56.9,3,0
216,C0217,M,47.0,Seoul,2024-12-09,Standard,Card,44.1,4,33.8,5,0
219,C0220,M,31.0,NaN,2025-08-21,Basic,Bank,36.0,2,19.7,3,0

In [10]:
import pandas as pd

df = pd.read_csv('aice_associate_customer_churn.csv')

In [11]:
df.head()

,customer_id,gender,age,city,signup_date,plan_type,payment_method,monthly_usage_hours,support_calls,monthly_fee,satisfaction_score,churn
0,C0001,F,42.0,Busan,2025-07-12,Standard,Bank,43.4,3,34.8,1,1
1,C0002,F,31.0,Seoul,2024-01-07,Standard,Card,25.3,2,33.6,3,0
2,C0003,F,38.0,Incheon,2025-04-15,Standard,Mobile,44.7,0,27.8,3,0
3,C0004,M,21.0,Busan,2024-03-22,Basic,Card,20.0,4,15.0,3,1
4,C0005,M,36.0,Incheon,2024-06-24,Standard,Bank,50.4,0,33.0,3,0

In [12]:
df.loc[df['age']>=30, 'monthly_fee'].mean()

np.float64(31.487943262411356)

In [13]:
df['age'].fillna(0)

0      42.0
1      31.0
2      38.0
3      21.0
4      36.0
       ...
215    27.0
216    47.0
217    19.0
218     0.0
219    31.0
Name: age, Length: 220, dtype: float64

In [14]:
df['age'].fillna(df['age'].mean())

0      42.000000
1      31.000000
2      38.000000
3      21.000000
4      36.000000
         ...
215    27.000000
216    47.000000
217    19.000000
218    34.168269
219    31.000000
Name: age, Length: 220, dtype: float64

In [15]:
df['age'] = df['age'].fillna(df['age'].mean())

In [16]:
df['age'].isnull().sum()

np.int64(0)

In [17]:
df['age'].median()

np.float64(34.16826923076923)

In [18]:
df['city'].mean()

TypeError: Cannot perform reduction 'mean' with string dtype

In [19]:

df['city'].mode()

0    Seoul
Name: city, dtype: str

In [20]:
df.['city'].mode()[0]

SyntaxError: invalid syntax (96761795.py, line 1)

In [21]:
df["city"].mode()[0]

'Seoul'

In [22]:
df['city'].mode()[0]

'Seoul'

In [23]:
df['city'].isnull().sum()

np.int64(9)

In [25]:
df['city'].fillna(df['city'].mode()[0])

0        Busan
1        Seoul
2      Incheon
3        Busan
4      Incheon
        ...
215      Seoul
216      Seoul
217    Incheon
218      Seoul
219      Seoul
Name: city, Length: 220, dtype: str

In [26]:
df['city'] = df['city'].fillna(df['city'].mode()[0])

In [27]:
df['city'].isnull().sum()

np.int64(0)

In [28]:
df['monthly_usage_hours'] = df['monthly_usage_hours'].fillna(df['monthly_usage_hours'].median())

In [29]:
df['monthly_usage_hours'].isnull().sum()

np.int64(0)

In [30]:
df.describe()

,age,monthly_usage_hours,support_calls,monthly_fee,satisfaction_score,churn
count,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000
mean,34.168269,39.045455,1.922727,30.374091,3.336364,0.263636
std,10.175876,17.034945,1.555204,13.559570,1.203323,0.441609
min,19.000000,4.700000,0.000000,13.400000,1.000000,0.000000
25%,27.750000,26.975000,1.000000,18.800000,3.000000,0.000000
50%,34.168269,38.000000,2.000000,29.600000,3.000000,0.000000
75%,40.000000,48.900000,3.000000,35.975000,4.000000,1.000000
max,101.000000,145.700000,6.000000,63.900000,5.000000,1.000000

In [31]:
df.dropna(subset=['age'])

,customer_id,gender,age,city,signup_date,plan_type,payment_method,monthly_usage_hours,support_calls,monthly_fee,satisfaction_score,churn
0,C0001,F,42.000000,Busan,2025-07-12,Standard,Bank,43.4,3,34.8,1,1
1,C0002,F,31.000000,Seoul,2024-01-07,Standard,Card,25.3,2,33.6,3,0
2,C0003,F,38.000000,Incheon,2025-04-15,Standard,Mobile,44.7,0,27.8,3,0
3,C0004,M,21.000000,Busan,2024-03-22,Basic,Card,20.0,4,15.0,3,1
4,C0005,M,36.000000,Incheon,2024-06-24,Standard,Bank,50.4,0,33.0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...
215,C0216,M,27.000000,Seoul,2025-05-20,Standard,Bank,38.3,5,28.0,4,1
216,C0217,M,47.000000,Seoul,2024-12-09,Standard,Card,44.1,4,33.8,5,0
217,C0218,F,19.000000,Incheon,2024-02-14,Basic,Card,41.5,5,16.5,4,0
218,C0219,F,34.168269,Seoul,2024-03-04,Basic,Bank,21.7,0,21.6,3,0
219,C0220,M,31.000000,Seoul,2025-08-21,Basic,Bank,36.0,2,19.7,3,0

In [32]:

df.isnull().sum()

customer_id            0
gender                 0
age                    0
city                   0
signup_date            0
plan_type              0
payment_method         0
monthly_usage_hours    0
support_calls          0
monthly_fee            0
satisfaction_score     0
churn                  0
dtype: int64

In [1]:
df.info()

NameError: name 'df' is not defined

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('aice_associate_customer_churn.csv')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          220 non-null    str
 1   gender               220 non-null    str
 2   age                  208 non-null    float64
 3   city                 211 non-null    str
 4   signup_date          220 non-null    str
 5   plan_type            220 non-null    str
 6   payment_method       220 non-null    str
 7   monthly_usage_hours  213 non-null    float64
 8   support_calls        220 non-null    int64
 9   monthly_fee          220 non-null    float64
 10  satisfaction_score   220 non-null    int64
 11  churn                220 non-null    int64
dtypes: float64(3), int64(3), str(6)
memory usage: 20.8 KB