In [1]:
import pandas as pd

df = pd.DataFrame({
     'name': ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
    'score': [70, 85, 90, 65, 80, 95, 75]
})

In [2]:
df[df['score'] >= 80]

  name  score
1    B     85
2    C     90
4    E     80
5    F     95

In [18]:
df[['name','score']]

  name  score
0    A     70
1    B     85
2    C     90
3    D     65
4    E     80
5    F     95
6    G     75

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    7 non-null      str
 1   score   7 non-null      int64
dtypes: int64(1), str(1)
memory usage: 244.0 bytes