In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import tensorflow as tf

print("환경설정 완료")
print("TensorFlow:", tf.__version__)

환경설정 완료
TensorFlow: 2.21.0

In [3]:
import pandas as pd

student = {
    "이름": ["철수","영희","민수","지영"],
    "나이": [20, 21, 22, 20],
    "점수": [90, 85, 100, 95]
}

df = pd.DataFrame(student)

df

   이름  나이   점수
0  철수  20   90
1  영희  21   85
2  민수  22  100
3  지영  20   95

In [12]:
df["점수"].mean()

np.float64(92.5)

In [14]:
df.head()
df.shape

(4, 3)

In [18]:
df["점수"].mean()

np.float64(92.5)

In [20]:
df[df["점수"]>=90]

   이름  나이   점수
0  철수  20   90
2  민수  22  100
3  지영  20   95