In [27]:
import pandas as pd

data = pd.read_csv('day18_regression.csv')

data.head()

,shipment_id,order_date,distance_km,weight_kg,traffic_level,weather,vehicle_type,priority,driver_experience_years,warehouse_wait_min,package_type,temperature_c,delivery_time_min
0,SHP00001,2026-05-24,23.9,5.0,high,clear,car,normal,5.5,22.5,fragile,1.2,94.4
1,SHP00002,2026-07-06,122.1,10.8,high,clear,car,express,0.0,12.6,large,28.4,166.0
2,SHP00003,2026-07-03,40.5,8.3,high,clear,van,normal,5.1,8.8,large,18.6,104.6
3,SHP00004,2026-06-08,100.2,7.2,medium,clear,van,express,8.7,22.8,large,1.7,144.2
4,SHP00005,2026-07-05,87.5,14.8,medium,clear,car,express,7.7,87.6,small,2.3,178.2

In [28]:
print(data.shape)
print(data.info())
print(data.isnull().sum())

(520, 13)
<class 'pandas.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   shipment_id              520 non-null    str
 1   order_date               520 non-null    str
 2   distance_km              520 non-null    float64
 3   weight_kg                502 non-null    float64
 4   traffic_level            520 non-null    str
 5   weather                  506 non-null    str
 6   vehicle_type             520 non-null    str
 7   priority                 520 non-null    str
 8   driver_experience_years  500 non-null    float64
 9   warehouse_wait_min       520 non-null    float64
 10  package_type             508 non-null    str
 11  temperature_c            520 non-null    float64
 12  delivery_time_min        520 non-null    float64
dtypes: float64(6), str(7)
memory usage: 52.9 KB
None
shipment_id                 0
order_date                  0
distance_km                 0
weight_kg                  18
traffic_level               0
weather                    14
vehicle_type                0
priority                    0
driver_experience_years    20
warehouse_wait_min          0
package_type               12
temperature_c               0
delivery_time_min           0
dtype: int64

In [29]:
data['order_date'] = pd.to_datetime(data['order_date'])

data['order_month'] = data['order_date'].dt.month
data['order_day'] = data['order_date'].dt.day
data['order_dayofweek'] = data['order_date'].dt.day_of_week

data = data.drop(columns=['order_date'])

In [30]:
data.head()

,shipment_id,distance_km,weight_kg,traffic_level,weather,vehicle_type,priority,driver_experience_years,warehouse_wait_min,package_type,temperature_c,delivery_time_min,order_month,order_day,order_dayofweek
0,SHP00001,23.9,5.0,high,clear,car,normal,5.5,22.5,fragile,1.2,94.4,5,24,6
1,SHP00002,122.1,10.8,high,clear,car,express,0.0,12.6,large,28.4,166.0,7,6,0
2,SHP00003,40.5,8.3,high,clear,van,normal,5.1,8.8,large,18.6,104.6,7,3,4
3,SHP00004,100.2,7.2,medium,clear,van,express,8.7,22.8,large,1.7,144.2,6,8,0
4,SHP00005,87.5,14.8,medium,clear,car,express,7.7,87.6,small,2.3,178.2,7,5,6

In [31]:
data['weight_kg'] = data['weight_kg'].fillna(data['weight_kg'].median())
data['driver_experience_years'] = data['driver_experience_years'].fillna(data['driver_experience_years'].median())
data['weather'] = data['weather'].fillna(data['weather'].mode()[0])
data['package_type'] = data['package_type'].fillna(data['package_type'].mode()[0])

In [32]:
data.head()

,shipment_id,distance_km,weight_kg,traffic_level,weather,vehicle_type,priority,driver_experience_years,warehouse_wait_min,package_type,temperature_c,delivery_time_min,order_month,order_day,order_dayofweek
0,SHP00001,23.9,5.0,high,clear,car,normal,5.5,22.5,fragile,1.2,94.4,5,24,6
1,SHP00002,122.1,10.8,high,clear,car,express,0.0,12.6,large,28.4,166.0,7,6,0
2,SHP00003,40.5,8.3,high,clear,van,normal,5.1,8.8,large,18.6,104.6,7,3,4
3,SHP00004,100.2,7.2,medium,clear,van,express,8.7,22.8,large,1.7,144.2,6,8,0
4,SHP00005,87.5,14.8,medium,clear,car,express,7.7,87.6,small,2.3,178.2,7,5,6

In [33]:
data.shape

(520, 15)

In [34]:
Q1 = data['warehouse_wait_min'].quantile(0.25)
Q3 = data['warehouse_wait_min'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

data = data[
  (data['warehouse_wait_min']>=lower)&
  (data['warehouse_wait_min']<=upper)
  ]

data.shape

(512, 15)

In [35]:
data['traffic_level'] = data['traffic_level'].map({
  'low':0,
  'medium':1,
  'high':2
})

data = pd.get_dummies(data, columns=['weather','vehicle_type','priority','package_type'], dtype=int)

In [36]:
data.head()

,shipment_id,distance_km,weight_kg,traffic_level,driver_experience_years,warehouse_wait_min,temperature_c,delivery_time_min,order_month,order_day,...,vehicle_type_bike,vehicle_type_car,vehicle_type_van,priority_express,priority_normal,priority_same_day,package_type_fragile,package_type_large,package_type_medium,package_type_small
0,SHP00001,23.9,5.0,2,5.5,22.5,1.2,94.4,5,24,...,0,1,0,0,1,0,1,0,0,0
1,SHP00002,122.1,10.8,2,0.0,12.6,28.4,166.0,7,6,...,0,1,0,1,0,0,0,1,0,0
2,SHP00003,40.5,8.3,2,5.1,8.8,18.6,104.6,7,3,...,0,0,1,0,1,0,0,1,0,0
3,SHP00004,100.2,7.2,1,8.7,22.8,1.7,144.2,6,8,...,0,0,1,1,0,0,0,1,0,0
5,SHP00006,89.1,8.5,1,6.2,8.2,-2.8,155.8,5,20,...,0,0,1,0,1,0,0,0,1,0

In [39]:
x = data.drop(columns=['shipment_id', 'delivery_time_min'])

In [40]:
y = data['delivery_time_min']

print(x.shape)
print(y.shape)

(512, 22)
(512,)

In [42]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
  x,
  y,
  test_size=0.2,
  random_state=42 # 회귀문제 straitify 사용안함
)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(409, 22)
(103, 22)
(409,)
(103,)

In [43]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

print(x_train_scaled.shape)
print(x_test_scaled.shape)

(409, 22)
(103, 22)

In [45]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

lr = LinearRegression()
dt = DecisionTreeRegressor(random_state=42)
rf = RandomForestRegressor(random_state=42)

lr.fit(x_train_scaled, y_train)
dt.fit(x_train, y_train)
rf.fit(x_train, y_train);

In [46]:
lr_pred = lr.predict(x_test_scaled)
dt_pred = dt.predict(x_test)
rf_pred = rf.predict(x_test)

In [50]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def evaluate_regression(y_test, pred):
  mae = mean_absolute_error(y_test, pred)
  mse = mean_squared_error(y_test, pred)
  rmse = np.sqrt(mse)
  r2 = r2_score(y_test, pred)

  print("MAE :", mae)
  print("MSE :", mse)
  print("RMSE:", rmse)
  print("R2  :", r2)
  print()


evaluate_regression(y_test, lr_pred)
evaluate_regression(y_test, dt_pred)
evaluate_regression(y_test, rf_pred)

MAE : 7.348477115284269
MSE : 95.24658030617674
RMSE: 9.759435450177266
R2  : 0.9646469677139141

MAE : 18.67087378640776
MSE : 580.6369902912621
RMSE: 24.096410319615288
R2  : 0.7844827793472859

MAE : 13.563902912621359
MSE : 293.76459071844636
RMSE: 17.139562150721538
R2  : 0.8909622893883095

In [58]:
# 딥러닝 회귀
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input


model = Sequential([
  Input(shape=(x_train_scaled.shape[1],)),
  Dense(64, activation='relu'),
  Dropout(0.2),
  Dense(32, activation='relu'),
  Dense(1, activation='linear')
])

model.compile(
  optimizer='adam',
  loss='mean_squared_error',
  metrics=['mae']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [59]:
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

estop = EarlyStopping(
  monitor='val_loss',
  patience=10,
  restore_best_weights=True
)

checkpoint = ModelCheckpoint(
  filepath='best_regression_model.keras',
  monitor='val_loss',
  save_best_only=True
)

history = model.fit(
  x_train_scaled,
  y_train,
  epochs=100,
  batch_size=32,
  validation_split=0.2,
  callbacks=[estop, checkpoint]
)

Epoch 1/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 20395.3750 - mae: 134.5874 - val_loss: 19849.8594 - val_mae: 134.0329
Epoch 2/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 20217.3867 - mae: 133.9060 - val_loss: 19676.8438 - val_mae: 133.3821
Epoch 3/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 20034.3203 - mae: 133.2382 - val_loss: 19491.9961 - val_mae: 132.6851
Epoch 4/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 19826.9121 - mae: 132.4474 - val_loss: 19264.9082 - val_mae: 131.8258
Epoch 5/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 19560.6523 - mae: 131.4777 - val_loss: 18977.5645 - val_mae: 130.7385
Epoch 6/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 19218.9180 - mae: 130.1937 - val_loss: 18619.3379 - val_mae: 129.3801
Epoch 7/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 18815.3359 - mae: 128.7050 - val_loss: 18184.7891 - val_mae: 127.7227
Epoch 8/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 18321.9668 - mae: 126.8007 - val_loss: 17659.2109 - val_mae: 125.7105
Epoch 9/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 17714.1758 - mae: 124.4683 - val_loss: 17038.3184 - val_mae: 123.3073
Epoch 10/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 16995.2891 - mae: 121.7350 - val_loss: 16309.5166 - val_mae: 120.4463
Epoch 11/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 16178.1650 - mae: 118.4633 - val_loss: 15468.1445 - val_mae: 117.0731
Epoch 12/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 15252.7705 - mae: 114.7206 - val_loss: 14509.0322 - val_mae: 113.1279
Epoch 13/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14136.5186 - mae: 110.1156 - val_loss: 13437.2529 - val_mae: 108.5690
Epoch 14/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12945.2324 - mae: 104.9801 - val_loss: 12246.3857 - val_mae: 103.2909
Epoch 15/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 11634.2812 - mae: 98.8405 - val_loss: 10948.9521 - val_mae: 97.2583
Epoch 16/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10278.5977 - mae: 92.3425 - val_loss: 9632.7861 - val_mae: 90.7250
Epoch 17/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8844.0723 - mae: 84.8075 - val_loss: 8265.0283 - val_mae: 83.4180
Epoch 18/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7426.5435 - mae: 76.9347 - val_loss: 6922.1265 - val_mae: 75.5524
Epoch 19/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6185.6416 - mae: 69.1081 - val_loss: 5661.5303 - val_mae: 67.6197
Epoch 20/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4749.2212 - mae: 59.7436 - val_loss: 4498.2339 - val_mae: 59.5169
Epoch 21/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3642.1819 - mae: 51.0027 - val_loss: 3495.3877 - val_mae: 51.5436
Epoch 22/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2818.8757 - mae: 44.5775 - val_loss: 2681.3357 - val_mae: 44.2268
Epoch 23/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2043.3192 - mae: 37.1209 - val_loss: 2027.4019 - val_mae: 37.8266
Epoch 24/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1567.6890 - mae: 31.8989 - val_loss: 1528.9873 - val_mae: 32.3254
Epoch 25/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1144.5675 - mae: 26.3889 - val_loss: 1146.7483 - val_mae: 27.7582
Epoch 26/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1085.3636 - mae: 25.7644 - val_loss: 887.9528 - val_mae: 24.4237
Epoch 27/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 784.5761 - mae: 22.0701 - val_loss: 702.1943 - val_mae: 21.7775
Epoch 28/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 708.7838 - mae: 21.1479 - val_loss: 576.7716 - val_mae: 19.6821
Epoch 29/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 562.5671 - mae: 18.3559 - val_loss: 499.5311 - val_mae: 18.2972
Epoch 30/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 554.7184 - mae: 19.0507 - val_loss: 443.3752 - val_mae: 17.3312
Epoch 31/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 459.0455 - mae: 17.3547 - val_loss: 402.5401 - val_mae: 16.5800
Epoch 32/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 493.1036 - mae: 17.6191 - val_loss: 374.6418 - val_mae: 16.0069
Epoch 33/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 428.6182 - mae: 16.4327 - val_loss: 348.3472 - val_mae: 15.4904
Epoch 34/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 440.8839 - mae: 16.2281 - val_loss: 327.8247 - val_mae: 15.0951
Epoch 35/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 393.1078 - mae: 15.5505 - val_loss: 310.2879 - val_mae: 14.7767
Epoch 36/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 408.5619 - mae: 15.9760 - val_loss: 296.1663 - val_mae: 14.4837
Epoch 37/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 433.3857 - mae: 16.5284 - val_loss: 284.3439 - val_mae: 14.2089
Epoch 38/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 382.9597 - mae: 15.5195 - val_loss: 272.8896 - val_mae: 13.9631
Epoch 39/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 449.8415 - mae: 16.7176 - val_loss: 263.7358 - val_mae: 13.7675
Epoch 40/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 426.3306 - mae: 16.5144 - val_loss: 258.5695 - val_mae: 13.6135
Epoch 41/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 348.2401 - mae: 14.7947 - val_loss: 256.9633 - val_mae: 13.5361
Epoch 42/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 377.1457 - mae: 15.4223 - val_loss: 255.5484 - val_mae: 13.4703
Epoch 43/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 370.8683 - mae: 15.3945 - val_loss: 255.6433 - val_mae: 13.4704
Epoch 44/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 334.4753 - mae: 14.8948 - val_loss: 256.7032 - val_mae: 13.5043
Epoch 45/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 341.9649 - mae: 15.0298 - val_loss: 255.8250 - val_mae: 13.4828
Epoch 46/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 349.8476 - mae: 14.8714 - val_loss: 255.3585 - val_mae: 13.4587
Epoch 47/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 355.4316 - mae: 14.7166 - val_loss: 254.7620 - val_mae: 13.4483
Epoch 48/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 332.8776 - mae: 14.7413 - val_loss: 251.7635 - val_mae: 13.3811
Epoch 49/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 343.3501 - mae: 14.6264 - val_loss: 250.6993 - val_mae: 13.3633
Epoch 50/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 372.7402 - mae: 15.4016 - val_loss: 244.6511 - val_mae: 13.1700
Epoch 51/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 348.4924 - mae: 15.2228 - val_loss: 243.6344 - val_mae: 13.1226
Epoch 52/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 393.4078 - mae: 15.8984 - val_loss: 241.7529 - val_mae: 13.0221
Epoch 53/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 382.4986 - mae: 15.1561 - val_loss: 241.1397 - val_mae: 13.0048
Epoch 54/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 347.8660 - mae: 14.4667 - val_loss: 238.4423 - val_mae: 12.9451
Epoch 55/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 341.6508 - mae: 14.6134 - val_loss: 232.4217 - val_mae: 12.7893
Epoch 56/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 364.8555 - mae: 15.5395 - val_loss: 228.5844 - val_mae: 12.6801
Epoch 57/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 342.1032 - mae: 14.4418 - val_loss: 232.7622 - val_mae: 12.8336
Epoch 58/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 320.2254 - mae: 14.2986 - val_loss: 232.1188 - val_mae: 12.7757
Epoch 59/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 309.4846 - mae: 13.7359 - val_loss: 229.6610 - val_mae: 12.6901
Epoch 60/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 316.2952 - mae: 14.3421 - val_loss: 225.5718 - val_mae: 12.6276
Epoch 61/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 313.0267 - mae: 13.9655 - val_loss: 224.5693 - val_mae: 12.5820
Epoch 62/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 327.5378 - mae: 14.2128 - val_loss: 221.0962 - val_mae: 12.4630
Epoch 63/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 288.6747 - mae: 13.3758 - val_loss: 220.5954 - val_mae: 12.4384
Epoch 64/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 311.6581 - mae: 14.0183 - val_loss: 221.6656 - val_mae: 12.4490
Epoch 65/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 327.2109 - mae: 14.5587 - val_loss: 219.5904 - val_mae: 12.2856
Epoch 66/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 313.4744 - mae: 13.7951 - val_loss: 214.0540 - val_mae: 12.0620
Epoch 67/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 324.7944 - mae: 14.3042 - val_loss: 212.8952 - val_mae: 12.1129
Epoch 68/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 329.5972 - mae: 14.2894 - val_loss: 213.3671 - val_mae: 12.0936
Epoch 69/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 282.0052 - mae: 13.0921 - val_loss: 213.0589 - val_mae: 12.0619
Epoch 70/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 287.0514 - mae: 13.2264 - val_loss: 213.6632 - val_mae: 12.0611
Epoch 71/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 308.4262 - mae: 13.8204 - val_loss: 214.3071 - val_mae: 12.0936
Epoch 72/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 288.5145 - mae: 13.5634 - val_loss: 216.2912 - val_mae: 12.2463
Epoch 73/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 296.6635 - mae: 13.4345 - val_loss: 218.6439 - val_mae: 12.3652
Epoch 74/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 303.7306 - mae: 13.7421 - val_loss: 220.4571 - val_mae: 12.4725
Epoch 75/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 303.3091 - mae: 13.5048 - val_loss: 222.4266 - val_mae: 12.5131
Epoch 76/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 291.8620 - mae: 13.1882 - val_loss: 212.2824 - val_mae: 12.1894
Epoch 77/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 289.0083 - mae: 13.3447 - val_loss: 208.6321 - val_mae: 12.0887
Epoch 78/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 312.8530 - mae: 13.5598 - val_loss: 207.5335 - val_mae: 12.0633
Epoch 79/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 316.2288 - mae: 14.0547 - val_loss: 212.0878 - val_mae: 12.1830
Epoch 80/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 320.6826 - mae: 14.1210 - val_loss: 212.0647 - val_mae: 12.2337
Epoch 81/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 273.0224 - mae: 12.8939 - val_loss: 208.3864 - val_mae: 12.1714
Epoch 82/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 250.3551 - mae: 12.3703 - val_loss: 206.4164 - val_mae: 12.0465
Epoch 83/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 338.6795 - mae: 14.0431 - val_loss: 204.5257 - val_mae: 11.9552
Epoch 84/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 314.9246 - mae: 13.7311 - val_loss: 205.8577 - val_mae: 11.9330
Epoch 85/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 268.5221 - mae: 12.9937 - val_loss: 201.8334 - val_mae: 11.7449
Epoch 86/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 272.8311 - mae: 12.5287 - val_loss: 210.0817 - val_mae: 12.0333
Epoch 87/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 310.4618 - mae: 13.9739 - val_loss: 206.6294 - val_mae: 11.9710
Epoch 88/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 285.7722 - mae: 13.4008 - val_loss: 201.0238 - val_mae: 11.8549
Epoch 89/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 248.2986 - mae: 12.4617 - val_loss: 197.4208 - val_mae: 11.7629
Epoch 90/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 265.2248 - mae: 12.5937 - val_loss: 199.4170 - val_mae: 11.8232
Epoch 91/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 292.1775 - mae: 13.4418 - val_loss: 197.6249 - val_mae: 11.7247
Epoch 92/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 253.3500 - mae: 12.5581 - val_loss: 196.4675 - val_mae: 11.5965
Epoch 93/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 271.4377 - mae: 13.3847 - val_loss: 195.1495 - val_mae: 11.5311
Epoch 94/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 279.3755 - mae: 13.1314 - val_loss: 195.3212 - val_mae: 11.5171
Epoch 95/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 240.1250 - mae: 12.0326 - val_loss: 191.7281 - val_mae: 11.4225
Epoch 96/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 307.4145 - mae: 13.6865 - val_loss: 190.8186 - val_mae: 11.4448
Epoch 97/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 272.5054 - mae: 12.9534 - val_loss: 189.1914 - val_mae: 11.3709
Epoch 98/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 278.9264 - mae: 13.2286 - val_loss: 189.9117 - val_mae: 11.4045
Epoch 99/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 258.8022 - mae: 12.6755 - val_loss: 193.1676 - val_mae: 11.4814
Epoch 100/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 281.5031 - mae: 13.1493 - val_loss: 198.7545 - val_mae: 11.6455

In [60]:
# 회귀 딥러닝 mae, mse, rmse, r2
dl_pred = model.predict(x_test_scaled)

mae = mean_absolute_error(y_test, dl_pred)
mse = mean_squared_error(y_test, dl_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, dl_pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R2  :", r2)
print()

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
MAE : 11.944997687478669
MSE : 224.1950101242366
RMSE: 14.973142960789382
R2  : 0.9167846928905699