In [1]:
# 피벗테이블 생성
import numpy as np
import pandas as pd

pivot_data = pd.DataFrame({'cust_id':['cust_1', 'cust_1', 'cust_1', 'cust_2', 'cust_2', 'cust_2', 'cust_3', 'cust_3', 'cust_3'],
                           'prod_cd':['p1', 'p2', 'p3', 'p1', 'p2', 'p3', 'p1', 'p2', 'p3' ],
                           'grade':['A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B'],
                           'purch_amt':[30, 10, 0, 40, 15, 30, 0, 0, 10]})
pivot_data

  cust_id prod_cd grade  purch_amt
0  cust_1      p1     A         30
1  cust_1      p2     A         10
2  cust_1      p3     A          0
3  cust_2      p1     A         40
4  cust_2      p2     A         15
5  cust_2      p3     A         30
6  cust_3      p1     B          0
7  cust_3      p2     B          0
8  cust_3      p3     B         10

In [2]:
# pivot  활용하기
# pivot은 기본적으로 index, columns, values를 지정하여 구성할 수 있다

pivot1 = pivot_data.pivot(index='cust_id', columns='prod_cd', values='purch_amt')
pivot1

prod_cd  p1  p2  p3
cust_id
cust_1   30  10   0
cust_2   40  15  30
cust_3    0   0  10

In [ ]:
# 중복값이 존재하는 경우 pivot 사용 불가 
# 예를 들어 A행 p1 열에 100, 200 같은 값이 2개나 있을때 - 칸은 하나라서 오류
pivot_data.pivot(index='grade', columns='prod_cd', values='purch_amt')

ValueError: Index contains duplicate entries, cannot reshape

In [ ]:
# 피벗 테이블 - 위 에러를 반환하는게 아닌 컬럼들의 평균 값을 내버림
pivot_data.pivot_table(index='grade', columns='prod_cd', values='purch_amt')

prod_cd    p1    p2    p3
grade
A        35.0  12.5  15.0
B         0.0   0.0  10.0

In [10]:
# aggfunc의 기본이 평균값이라 위에서 평균값이 나옴. 다르게 지정도 가능
pivot_data.pivot_table(index='grade', columns='prod_cd', values='purch_amt', aggfunc=np.sum)

prod_cd  p1  p2  p3
grade
A        70  25  30
B         0   0  10