In [1]:
import numpy as np
import pandas as pd

stack_data = pd.DataFrame({
    'Location': ['Seoul', 'Seoul', 'Seoul', 'kyounggi', 'kyounggi', 'Busan', 'Seoul', 'Seoul', 'Busan', 'kyounggi', 'kyounggi', 'kyounggi'],
    'Day': ['Mon', 'Tue', 'Wed', 'Mon', 'Tue', 'Mon', 'Thu', 'Fri', 'Tue', 'Wed', 'Thu', 'Fri'],
    'Ranfall': [100, 80, 1000, 200, 200, 100, 50, 100, 200, 100, 50, 100],
    'Rainfall_precipitation': [80, 70, 90, 10, 20, 30, 50, 90, 20, 80, 50, 10],
    'Temp' : [32, 27, 32, 31, 30, 28, 27, 25, 26, 33, 34, 31]})

stack_data

    Location  Day  Ranfall  Rainfall_precipitation  Temp
0      Seoul  Mon      100                      80    32
1      Seoul  Tue       80                      70    27
2      Seoul  Wed     1000                      90    32
3   kyounggi  Mon      200                      10    31
4   kyounggi  Tue      200                      20    30
5      Busan  Mon      100                      30    28
6      Seoul  Thu       50                      50    27
7      Seoul  Fri      100                      90    25
8      Busan  Tue      200                      20    26
9   kyounggi  Wed      100                      80    33
10  kyounggi  Thu       50                      50    34
11  kyounggi  Fri      100                      10    31

In [ ]:
# 인덱스 설정하기(두 컬럼을 인덱스로)
new_stack_data = stack_data.set_index(['Location','Day'])
new_stack_data

              Ranfall  Rainfall_precipitation  Temp
Location Day
Seoul    Mon      100                      80    32
         Tue       80                      70    27
         Wed     1000                      90    32
kyounggi Mon      200                      10    31
         Tue      200                      20    30
Busan    Mon      100                      30    28
Seoul    Thu       50                      50    27
         Fri      100                      90    25
Busan    Tue      200                      20    26
kyounggi Wed      100                      80    33
         Thu       50                      50    34
         Fri      100                      10    31

In [ ]:
# unstack 확인하기 
# 인덱스 레벨에서 컬럼 레벨로 위치를 변경하여 데이터를 쌓아올리는것
# Location(0)이 컬럼 레벨로 올라감. 
new_stack_data.unstack(0)

         Ranfall                  Rainfall_precipitation                 Temp  \
Location   Busan   Seoul kyounggi                  Busan Seoul kyounggi Busan
Day
Fri          NaN   100.0    100.0                    NaN  90.0     10.0   NaN
Mon        100.0   100.0    200.0                   30.0  80.0     10.0  28.0
Thu          NaN    50.0     50.0                    NaN  50.0     50.0   NaN
Tue        200.0    80.0    200.0                   20.0  70.0     20.0  26.0
Wed          NaN  1000.0    100.0                    NaN  90.0     80.0   NaN


Location Seoul kyounggi
Day
Fri       25.0     31.0
Mon       32.0     31.0
Thu       27.0     34.0
Tue       27.0     30.0
Wed       32.0     33.0

In [7]:
new_stack_data.unstack(1)

         Ranfall                             Rainfall_precipitation        \
Day          Fri    Mon   Thu    Tue     Wed                    Fri   Mon
Location
Busan        NaN  100.0   NaN  200.0     NaN                    NaN  30.0
Seoul      100.0  100.0  50.0   80.0  1000.0                   90.0  80.0
kyounggi   100.0  200.0  50.0  200.0   100.0                   10.0  10.0

                            Temp
Day        Thu   Tue   Wed   Fri   Mon   Thu   Tue   Wed
Location
Busan      NaN  20.0   NaN   NaN  28.0   NaN  26.0   NaN
Seoul     50.0  70.0  90.0  25.0  32.0  27.0  27.0  32.0
kyounggi  50.0  20.0  80.0  31.0  31.0  34.0  30.0  33.0

In [ ]:
# stack - 컬럼 레벨에서 인덱스 레벨로 데이터프레임을 변경하는것 
# unstack한 데이터를 저장하고 stack을 적용하면 두 번째 컬럼 레벨에 있던 day가 다시 인덱스 레벨로 변경됨
new_stack_data2 = new_stack_data.unstack(1)
new_stack_data2.stack(1)

              Ranfall  Rainfall_precipitation  Temp
Location Day
Busan    Fri      NaN                     NaN   NaN
         Mon    100.0                    30.0  28.0
         Thu      NaN                     NaN   NaN
         Tue    200.0                    20.0  26.0
         Wed      NaN                     NaN   NaN
Seoul    Fri    100.0                    90.0  25.0
         Mon    100.0                    80.0  32.0
         Thu     50.0                    50.0  27.0
         Tue     80.0                    70.0  27.0
         Wed   1000.0                    90.0  32.0
kyounggi Fri    100.0                    10.0  31.0
         Mon    200.0                    10.0  31.0
         Thu     50.0                    50.0  34.0
         Tue    200.0                    20.0  30.0
         Wed    100.0                    80.0  33.0