In [1]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame({'col1' : ['사과','배','감','수박','메론'], 'col2' : [500, 1000, 2500, 5000,3000]}, index=[0,1,2,3,4])
df2 = pd.DataFrame({'col1' : ['수박','메론','딸기','키위','오렌지'], 'col2' : [5000,3000,1000,600,700]}, index=[3,4,5,6,7])

In [ ]:
# ignore_index = False -> 두 컬럼을 위 아래로 이어붙이기만 할 뿐, 고유 인덱스 처리는 해주지 않는다. (기존 인덱스 유지)
concat1 = pd.concat([df1, df2], ignore_index=False)
concat1

  col1  col2
0   사과   500
1    배  1000
2    감  2500
3   수박  5000
4   메론  3000
3   수박  5000
4   메론  3000
5   딸기  1000
6   키위   600
7  오렌지   700

In [ ]:
# ignore_index = True 새 인덱스 부여
concat2 = pd.concat([df1, df2], ignore_index=True)
concat2

  col1  col2
0   사과   500
1    배  1000
2    감  2500
3   수박  5000
4   메론  3000
5   수박  5000
6   메론  3000
7   딸기  1000
8   키위   600
9  오렌지   700

In [ ]:
# axis = 0 -> 행 레벨(default) - 가로
# axis = 1 -> 열 레벨 - 세로
# 여기서도 ignore index 가능
concat3 = pd.concat([df1, df2], axis=1, ignore_index=True)
concat3

     0       1    2       3
0   사과   500.0  NaN     NaN
1    배  1000.0  NaN     NaN
2    감  2500.0  NaN     NaN
3   수박  5000.0   수박  5000.0
4   메론  3000.0   메론  3000.0
5  NaN     NaN   딸기  1000.0
6  NaN     NaN   키위   600.0
7  NaN     NaN  오렌지   700.0

In [7]:
df3 = pd.DataFrame({'item':['item0','item1','item2', 'item3'], 'count':['count0','count1','count2','count3'],
                    'price':['price0','price1','price2','price3']}, index = [0,1,2,3])
df4 = pd.DataFrame({'item':['item2','item3','item4', 'item5'], 'count':['count2','count3','count4','count5'],
                    'price':['price2','price3','price4','price5'], 'var':['var2','var3','var4','var5']}, index = [2,3,4,5])

In [ ]:
# 컬럼명이 다른 경우 - join(outer 합집합) - 한쪽에 없어도 그냥 다 병합
concat4 = pd.concat([df3, df4], join='outer')
concat4

    item   count   price   var
0  item0  count0  price0   NaN
1  item1  count1  price1   NaN
2  item2  count2  price2   NaN
3  item3  count3  price3   NaN
2  item2  count2  price2  var2
3  item3  count3  price3  var3
4  item4  count4  price4  var4
5  item5  count5  price5  var5

In [ ]:
# inner 교집합 - 공통 컬럼만 병합
concat5 = pd.concat([df3, df4], join='inner')
concat5

    item   count   price
0  item0  count0  price0
1  item1  count1  price1
2  item2  count2  price2
3  item3  count3  price3
2  item2  count2  price2
3  item3  count3  price3
4  item4  count4  price4
5  item5  count5  price5

In [10]:
# 인덱스가 중복인 경우
df5 = pd.DataFrame({'A':['A0','A1','A2'], 'B':['B0','B1','B2'], 'C':['C0','C1','C2'], 'D':['D0','D1','D2']}, index=['I0','I1','I2'])
df6 = pd.DataFrame({'A':['AA2','A3','A4'], 'B':['BB2','B3','B4'], 'C':['CC2','C3','C4'], 'D':['DD2','D3','D4']}, index=['I2','I3','I4'])

In [13]:
# verify_integrity : 파라미터 값을 True로 변경하는 경우, 두 데이터프레임의 인덱스가 중복임을 알리는 에러 메시지를 출력
pd.concat([df5, df6], verify_integrity=True)

ValueError: Indexes have overlapping values: Index(['I2'], dtype='str')

In [14]:
# merge
customer = pd.DataFrame({'customer_id' : np.arange(6), 
                    'name' : ['James', 'Elly', 'Tom', 'Givert', 'Aiden', 'Brody'], 
                    '나이' : [40, 20, 21, 30, 31, 18]})

orders = pd.DataFrame({'customer_id' : [1, 1, 2, 2, 2, 3, 3, 1, 4, 9], 
                    'item' : ['마우스', '충전기', '이어폰', '헤드셋', '전자펜', '키보드', '전자펜', '마우스', '키보드', '케이스'], 
                    'quantity' : [1, 2, 1, 1, 3, 2, 2, 3, 2, 1]})

In [ ]:
# customer id 기준으로 merge
# 참고로 merge할 데이터는 '' 안붙임
merge1 = pd.merge(customer, orders, on='customer_id')
merge1

   customer_id    name  나이 item  quantity
0            1    Elly  20  마우스         1
1            1    Elly  20  충전기         2
2            1    Elly  20  마우스         3
3            2     Tom  21  이어폰         1
4            2     Tom  21  헤드셋         1
5            2     Tom  21  전자펜         3
6            3  Givert  30  키보드         2
7            3  Givert  30  전자펜         2
8            4   Aiden  31  키보드         2

In [ ]:
# how 속성 - join 과 유사
# merge / how='inner'가 기본값이라 동일한 결과를 얻음
merge2 = pd.merge(customer, orders, on='customer_id', how='inner')
merge2

   customer_id    name  나이 item  quantity
0            1    Elly  20  마우스         1
1            1    Elly  20  충전기         2
2            1    Elly  20  마우스         3
3            2     Tom  21  이어폰         1
4            2     Tom  21  헤드셋         1
5            2     Tom  21  전자펜         3
6            3  Givert  30  키보드         2
7            3  Givert  30  전자펜         2
8            4   Aiden  31  키보드         2

In [ ]:
# left outer join 과 유사. orders에 없으면 nan
# 참고로 int에는 nan을 넣을 수 없어서 소수로 승격시킴
merge3 = pd.merge(customer, orders, on='customer_id', how='left')
merge3

    customer_id    name  나이 item  quantity
0             0   James  40  NaN       NaN
1             1    Elly  20  마우스       1.0
2             1    Elly  20  충전기       2.0
3             1    Elly  20  마우스       3.0
4             2     Tom  21  이어폰       1.0
5             2     Tom  21  헤드셋       1.0
6             2     Tom  21  전자펜       3.0
7             3  Givert  30  키보드       2.0
8             3  Givert  30  전자펜       2.0
9             4   Aiden  31  키보드       2.0
10            5   Brody  18  NaN       NaN

In [ ]:
# left 케이스의 반대
merge4 = pd.merge(customer, orders, on='customer_id', how='right')
merge4

   customer_id    name    나이 item  quantity
0            1    Elly  20.0  마우스         1
1            1    Elly  20.0  충전기         2
2            2     Tom  21.0  이어폰         1
3            2     Tom  21.0  헤드셋         1
4            2     Tom  21.0  전자펜         3
5            3  Givert  30.0  키보드         2
6            3  Givert  30.0  전자펜         2
7            1    Elly  20.0  마우스         3
8            4   Aiden  31.0  키보드         2
9            9     NaN   NaN  케이스         1

In [ ]:
# outer - customer_id를 모두 활용하여 병합한 결과를 보여줌(full outer)
merge5 = pd.merge(customer, orders, on='customer_id', how='outer')
merge5

    customer_id    name    나이 item  quantity
0             0   James  40.0  NaN       NaN
1             1    Elly  20.0  마우스       1.0
2             1    Elly  20.0  충전기       2.0
3             1    Elly  20.0  마우스       3.0
4             2     Tom  21.0  이어폰       1.0
5             2     Tom  21.0  헤드셋       1.0
6             2     Tom  21.0  전자펜       3.0
7             3  Givert  30.0  키보드       2.0
8             3  Givert  30.0  전자펜       2.0
9             4   Aiden  31.0  키보드       2.0
10            5   Brody  18.0  NaN       NaN
11            9     NaN   NaN  케이스       1.0

In [ ]:
# 인덱스를 지정하여 데이터 합치기 (인덱스를 지정하여 inner 형태로 가능)
cust1 = customer.set_index('customer_id')
order1 = orders.set_index('customer_id')

pd.merge(cust1, order1, left_index=True, right_index=True)

               name  나이 item  quantity
customer_id
1              Elly  20  마우스         1
1              Elly  20  충전기         2
1              Elly  20  마우스         3
2               Tom  21  이어폰         1
2               Tom  21  헤드셋         1
2               Tom  21  전자펜         3
3            Givert  30  키보드         2
3            Givert  30  전자펜         2
4             Aiden  31  키보드         2