In [1]:
import pandas as pd

df = pd.read_csv('aice_delivery_operations.csv')

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   order_id                  524 non-null    str
 1   order_date                524 non-null    str
 2   city                      524 non-null    str
 3   weather                   501 non-null    str
 4   traffic_level             524 non-null    str
 5   distance_km               516 non-null    float64
 6   items_count               524 non-null    int64
 7   prep_minutes              524 non-null    float64
 8   courier_experience_years  489 non-null    float64
 9   vehicle_type              524 non-null    str
 10  order_channel             524 non-null    str
 11  delivery_minutes          524 non-null    float64
dtypes: float64(4), int64(1), str(7)
memory usage: 49.3 KB

In [3]:
df.head()

,order_id,order_date,city,weather,traffic_level,distance_km,items_count,prep_minutes,courier_experience_years,vehicle_type,order_channel,delivery_minutes
0,ORD-20260147,2026-02-18,Busan,Clear,Medium,1.9,4,23.4,1.0,Scooter,Web,41.0
1,ORD-20260092,2026-04-04,Seoul,Cloudy,Low,8.1,5,21.6,7.6,Scooter,Web,51.9
2,ORD-20260336,2026-06-25,Daegu,Clear,High,7.2,2,20.0,3.7,Bike,App,58.7
3,ORD-20260381,2026-04-23,Seoul,Clear,Medium,6.4,4,19.5,1.4,Bike,App,48.0
4,ORD-20260507,2026-01-27,Daejeon,Clear,Medium,7.4,5,18.6,0.8,Scooter,App,46.1

In [4]:
df.isnull().sum()

order_id                     0
order_date                   0
city                         0
weather                     23
traffic_level                0
distance_km                  8
items_count                  0
prep_minutes                 0
courier_experience_years    35
vehicle_type                 0
order_channel                0
delivery_minutes             0
dtype: int64

In [ ]:
df.describe()

,distance_km,items_count,prep_minutes,courier_experience_years,delivery_minutes
count,516.000000,524.000000,524.000000,489.000000,524.000000
mean,6.307752,3.272901,20.034924,2.875869,50.030534
std,3.778033,1.543490,5.183296,1.699491,12.236529
min,0.400000,1.000000,5.700000,0.000000,19.300000
25%,4.000000,2.000000,16.800000,1.600000,41.575000
50%,5.900000,3.000000,19.900000,2.900000,49.150000
75%,8.100000,4.000000,23.500000,4.000000,57.325000
max,30.900000,9.000000,34.600000,7.800000,115.400000

In [ ]:
print(df['city'].value_counts(), '\n')
print(df['weather'].value_counts(dropna=False), '\n')
print(df['traffic_level'].value_counts(), '\n')
print(df['vehicle_type'].value_counts(), '\n')
print(df['order_channel'].value_counts(), '\n')

city
Seoul      181
Busan      111
Incheon     92
Daejeon     71
Daegu       69
Name: count, dtype: int64

weather
Clear     284
Cloudy    114
Rain       87
NaN        23
Snow       16
Name: count, dtype: int64

traffic_level
Medium    245
Low       142
High      137
Name: count, dtype: int64

order_channel
App      367
Web      129
Phone     28
Name: count, dtype: int64

In [15]:
df['weather'] = df['weather'].fillna(df['weather'].mode().iloc[0])
df['distance_km'] = df['distance_km'].fillna(df['distance_km'].median())
df['courier_experience_years'] = df['courier_experience_years'].fillna(df['courier_experience_years'].mean())

In [16]:
df.isnull().sum()

order_id                    0
order_date                  0
city                        0
weather                     0
traffic_level               0
distance_km                 0
items_count                 0
prep_minutes                0
courier_experience_years    0
vehicle_type                0
order_channel               0
delivery_minutes            0
dtype: int64

In [18]:
# 날짜 처리 
df['order_date'] = pd.to_datetime(df['order_date'])
df['order_date'].dtype

dtype('<M8[us]')

In [ ]:
# 년/월/일/요일/주말 날짜 컬럼
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
df['day'] = df['order_date'].dt.day
df['dayofweek'] = df['order_date'].dt.day_of_week
df['is_weekend'] = (df['dayofweek']>=5).astype(int)

df[['order_date', 'year', 'month', 'day', 'dayofweek', 'is_weekend']].head()

  order_date  year  month  day  dayofweek  is_weekend
0 2026-02-18  2026      2   18          2           0
1 2026-04-04  2026      4    4          5           1
2 2026-06-25  2026      6   25          3           0
3 2026-04-23  2026      4   23          3           0
4 2026-01-27  2026      1   27          1           0

In [22]:
df['traffic_level'] = df['traffic_level'].map({
    'Medium':0,
    'Low':1,
    'High':2
})

In [ ]:
# 이미 들어있는 컬럼 삭제
df.drop(columns=['order_date', 'year', 'day'], inplace=True)

In [26]:
df = pd.get_dummies(df, columns=['city', 'weather', 'vehicle_type', 'order_channel'])

In [31]:
df = df.drop(columns=['order_id'])

In [32]:
df.head()

,traffic_level,distance_km,items_count,prep_minutes,courier_experience_years,delivery_minutes,month,dayofweek,is_weekend,city_Busan,...,weather_Clear,weather_Cloudy,weather_Rain,weather_Snow,vehicle_type_Bike,vehicle_type_Car,vehicle_type_Scooter,order_channel_App,order_channel_Phone,order_channel_Web
0,0,1.9,4,23.4,1.0,41.0,2,2,0,True,...,True,False,False,False,False,False,True,False,False,True
1,1,8.1,5,21.6,7.6,51.9,4,5,1,False,...,False,True,False,False,False,False,True,False,False,True
2,2,7.2,2,20.0,3.7,58.7,6,3,0,False,...,True,False,False,False,True,False,False,True,False,False
3,0,6.4,4,19.5,1.4,48.0,4,3,0,False,...,True,False,False,False,True,False,False,True,False,False
4,0,7.4,5,18.6,0.8,46.1,1,1,0,False,...,True,False,False,False,False,False,True,True,False,False

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   traffic_level             524 non-null    int64
 1   distance_km               524 non-null    float64
 2   items_count               524 non-null    int64
 3   prep_minutes              524 non-null    float64
 4   courier_experience_years  524 non-null    float64
 5   delivery_minutes          524 non-null    float64
 6   month                     524 non-null    int32
 7   dayofweek                 524 non-null    int32
 8   is_weekend                524 non-null    int64
 9   city_Busan                524 non-null    bool
 10  city_Daegu                524 non-null    bool
 11  city_Daejeon              524 non-null    bool
 12  city_Incheon              524 non-null    bool
 13  city_Seoul                524 non-null    bool
 14  weather_Clear             524 non-null    bool
 15  weather_Cloudy            524 non-null    bool
 16  weather_Rain              524 non-null    bool
 17  weather_Snow              524 non-null    bool
 18  vehicle_type_Bike         524 non-null    bool
 19  vehicle_type_Car          524 non-null    bool
 20  vehicle_type_Scooter      524 non-null    bool
 21  order_channel_App         524 non-null    bool
 22  order_channel_Phone       524 non-null    bool
 23  order_channel_Web         524 non-null    bool
dtypes: bool(15), float64(4), int32(2), int64(3)
memory usage: 40.6 KB

In [36]:
import numpy as np

a = np.array([10, 20, 30, 40 ,50]) * 2
a

array([ 20,  40,  60,  80, 100])

In [38]:
b = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(b.shape)
print(b.ndim)
print(b.dtype)

(2, 3)
2
int64

In [ ]:
# 일반적인 인덱스와 동일하게 행 - 열 (0부터 시작)
# 2차원 배열이면 몇번째 배열(행), 몆번째 행 
b[1,2]

np.int64(60)

In [ ]:
print(b[0,:]) # 0 번째 행 전체
print(b[:,2]) # 모든 행 2열
print(b[:,:]) # 모든 행
print(b[0:2, 0:2]) # 0,1번 행/0,1번 열 까지

[10 20 30]
[30 60]
[[10 20 30]
 [40 50 60]]
[[10 20]
 [40 50]]

In [66]:
x = np.array([15, 22, 37, 41, 58, 63]) 

print(np.mean(x))
print(x[x>=40])
print(x[(x >= 20)&(x < 60)])

39.333333333333336
[41 58 63]
[22 37 41 58]

In [88]:
test_group = df.groupby('month')
test_group.mean()[['is_weekend']]

       is_weekend
month
1        0.263158
2        0.223684
3        0.231884
4        0.273810
5        0.428571
6        0.236111
7        0.329268

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le_df = pd.DataFrame({
    'study_hours': [2, 5, 3, 8, 7, 1],
    'attendance': [70, 90, 80, 95, 92, 60],
    'result': ['Fail', 'Pass', 'Fail', 'Pass', 'Pass', 'Fail']
})

# 인코딩 규칙 학습
le_df['result'] = le.fit_transform(le_df['result'])

le_df.head()

   study_hours  attendance  result
0            2          70       0
1            5          90       1
2            3          80       0
3            8          95       1
4            7          92       1

In [92]:
le.classes_

array(['Fail', 'Pass'], dtype=object)

In [95]:
# x / y 분리
from sklearn.model_selection import train_test_split

x = df.drop(columns=['delivery_minutes'])
y = df['delivery_minutes']

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
# 스케일링
# 평균 기준으로 얼마나 떨어져 있는지 보여줘서 음/양수 섞임
from sklearn.preprocessing import StandardScaler

st_scale = StandardScaler()

st_x_train_scaled = st_scale.fit_transform(x_train)
st_x_test_scaled = st_scale.transform(x_test)

In [ ]:
# 전부 0~1 범위 쪽으로 누름
from sklearn.preprocessing import MinMaxScaler

mm_scale = MinMaxScaler()

mm_x_train_scaled = mm_scale.fit_transform(x_train)
mm_x_test_scaled = mm_scale.transform(x_test)

In [ ]:
# 중앙값과 IQR 기준이라 값 분포가 다르게 보임
from sklearn.preprocessing import RobustScaler

rb_scale = RobustScaler()

rb_x_train_scaled = rb_scale.fit_transform(x_train)
rb_x_train_scaled = rb_scale.transform(x_test)

In [107]:
# 스케일러 별 비교 (5개행씩)
print(st_x_train_scaled[:5, 1])
print(mm_x_train_scaled[:5, 1])
print(rb_x_train_scaled[:5, 1])
x_train.columns.get_loc('distance_km')

[-0.6123488  -0.50070988  0.11330418  1.03432526  0.81104742]
[0.13261649 0.14695341 0.22580645 0.34408602 0.31541219]
[-0.8974359  -1.41025641  0.87179487 -0.33333333  0.8974359 ]

1

In [108]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train, y_train)

pred = lr.predict(x_test)

In [110]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, pred)
mae

4.502101912459457

In [ ]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, pred)
print(mse)
# rmse - mse를 분으로 변환
print(np.sqrt(mse))

31.000788064189493
5.567835132633642

In [114]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, pred)

r2

0.8506214420943844

In [115]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(x_train, y_train)
pred2 = model.predict(x_test)

mse = mean_squared_error(y_test, pred2)

print(mean_absolute_error(y_test, pred2))
print(mse)
print(np.sqrt(mse))
print(r2_score(y_test, pred2))

4.502101912459457
31.000788064189493
5.567835132633642
0.8506214420943844