In [1]:
import pandas as pd

df = pd.read_csv('aice_day5_practice.csv')

In [2]:
df.head()

,customer_id,age,gender,city,monthly_fee,tenure_months,support_calls,plan,contract_type,usage_gb,churn
0,1,60.0,M,Busan,60000.0,32,3,Basic,TwoYear,16.8,0
1,2,25.0,F,Busan,28000.0,12,3,Basic,TwoYear,74.2,0
2,3,32.0,F,Seoul,82000.0,36,0,Basic,TwoYear,NaN,0
3,4,29.0,M,Daegu,38000.0,12,6,Basic,OneYear,102.5,1
4,5,36.0,M,Incheon,93000.0,16,6,Basic,TwoYear,38.7,1

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    120 non-null    int64
 1   age            113 non-null    float64
 2   gender         120 non-null    str
 3   city           115 non-null    str
 4   monthly_fee    114 non-null    float64
 5   tenure_months  120 non-null    int64
 6   support_calls  120 non-null    int64
 7   plan           115 non-null    str
 8   contract_type  120 non-null    str
 9   usage_gb       114 non-null    float64
 10  churn          120 non-null    int64
dtypes: float64(3), int64(4), str(4)
memory usage: 10.4 KB

In [4]:
df.isnull().sum()

customer_id      0
age              7
gender           0
city             5
monthly_fee      6
tenure_months    0
support_calls    0
plan             5
contract_type    0
usage_gb         6
churn            0
dtype: int64

In [5]:
df['age'] = df['age'].fillna(df['age'].mean())
df['monthly_fee'] = df['monthly_fee'].fillna(df['monthly_fee'].median())
df['usage_gb'] = df['usage_gb'].fillna(df['usage_gb'].mean())
df['city'] = df['city'].fillna(df['city'].mode().iloc[0])
df['plan'] = df['plan'].fillna(df['plan'].mode().iloc[0])

In [6]:
df.isnull().sum()

customer_id      0
age              0
gender           0
city             0
monthly_fee      0
tenure_months    0
support_calls    0
plan             0
contract_type    0
usage_gb         0
churn            0
dtype: int64

In [26]:
df.head()

,customer_id,age,gender,monthly_fee,tenure_months,support_calls,usage_gb,churn,plan_Basic,plan_Premium,plan_Standard,contract_type_Monthly,contract_type_OneYear,contract_type_TwoYear,city_Busan,city_Daegu,city_Incheon,city_Seoul
0,1,60.0,0,60000.0,32,3,16.800000,0,True,False,False,False,False,True,True,False,False,False
1,2,25.0,1,28000.0,12,3,74.200000,0,True,False,False,False,False,True,True,False,False,False
2,3,32.0,1,82000.0,36,0,65.504386,0,True,False,False,False,False,True,False,False,False,True
3,4,29.0,0,38000.0,12,6,102.500000,1,True,False,False,False,True,False,False,True,False,False
4,5,36.0,0,93000.0,16,6,38.700000,1,True,False,False,False,False,True,False,False,True,False

In [8]:
df['gender'] = df['gender'].map({'M':0,'F':1})

In [17]:
df['plan'].value_counts()

plan
Basic       46
Premium     39
Standard    35
Name: count, dtype: int64

In [19]:
df = pd.get_dummies(df, columns=['plan'])

In [21]:
df['contract_type'].value_counts()

contract_type
TwoYear    44
Monthly    40
OneYear    36
Name: count, dtype: int64

In [22]:
df = pd.get_dummies(df, columns=['contract_type'])

In [24]:
df['city'].value_counts()

city
Incheon    40
Busan      34
Seoul      24
Daegu      22
Name: count, dtype: int64

In [25]:
df = pd.get_dummies(df, columns=['city'])

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customer_id            120 non-null    int64
 1   age                    120 non-null    float64
 2   gender                 120 non-null    int64
 3   monthly_fee            120 non-null    float64
 4   tenure_months          120 non-null    int64
 5   support_calls          120 non-null    int64
 6   usage_gb               120 non-null    float64
 7   churn                  120 non-null    int64
 8   plan_Basic             120 non-null    bool
 9   plan_Premium           120 non-null    bool
 10  plan_Standard          120 non-null    bool
 11  contract_type_Monthly  120 non-null    bool
 12  contract_type_OneYear  120 non-null    bool
 13  contract_type_TwoYear  120 non-null    bool
 14  city_Busan             120 non-null    bool
 15  city_Daegu             120 non-null    bool
 16  city_Incheon           120 non-null    bool
 17  city_Seoul             120 non-null    bool
dtypes: bool(10), float64(3), int64(5)
memory usage: 8.8 KB

In [28]:
df.head()

,customer_id,age,gender,monthly_fee,tenure_months,support_calls,usage_gb,churn,plan_Basic,plan_Premium,plan_Standard,contract_type_Monthly,contract_type_OneYear,contract_type_TwoYear,city_Busan,city_Daegu,city_Incheon,city_Seoul
0,1,60.0,0,60000.0,32,3,16.800000,0,True,False,False,False,False,True,True,False,False,False
1,2,25.0,1,28000.0,12,3,74.200000,0,True,False,False,False,False,True,True,False,False,False
2,3,32.0,1,82000.0,36,0,65.504386,0,True,False,False,False,False,True,False,False,False,True
3,4,29.0,0,38000.0,12,6,102.500000,1,True,False,False,False,True,False,False,True,False,False
4,5,36.0,0,93000.0,16,6,38.700000,1,True,False,False,False,False,True,False,False,True,False

In [29]:
x = df.drop(['churn', 'customer_id'], axis=1)
y =df['churn']

In [30]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test= train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

model = DecisionTreeClassifier(random_state=42)

model.fit(x_train, y_train)
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

train_acc = accuracy_score(y_train, train_pred)
test_acc = accuracy_score(y_test, test_pred)

print(train_acc, test_acc) 
# 1.0 / 0.8333... 
# max_depth를 주지 않은 상태에서 계속 분기하면서 과적합이 됐을 가능성이 높다

1.0
 0.8333333333333334

In [40]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    model,
    x_train,
    y_train,
    cv=5,
    scoring='accuracy'
)

print(scores)
print(scores.mean())

[0.85       0.68421053 0.84210526 0.84210526 0.73684211]
0.7910526315789473

In [ ]:
from sklearn.model_selection import GridSearchCV

# 최적의 max_depth 하이퍼파라미터 찾기
params = {
    'max_depth': [2, 3, 4, 5, 6, 7, 8, 10]
}

grid = GridSearchCV(
    model,
    params,
    cv=5, # 총 40회의 cv학습이 이루어짐. 기본이 refit=true 이기 때문에 +1 -> 41회
    scoring='accuracy'
)

grid.fit(x_train, y_train)

print(grid.best_params_)
print(grid.best_score_)
# 이미 최적 파라미터로 다시 학습된 모델
print(grid.best_estimator_)

{'max_depth': 3}
0.8226315789473684
DecisionTreeClassifier(max_depth=3, random_state=42)

In [42]:
# 최적 파라미터로 다시 학습된 모델로 테스트
best_model = grid.best_estimator_

final_pred = best_model.predict(x_test)

final_acc = accuracy_score(y_test, final_pred)

final_acc

0.8333333333333334

In [46]:
params2 = {
    'max_depth':[2, 3, 4, 5],
    'min_samples_split':[2, 5, 10],
    'min_samples_leaf':[1, 2, 4]
}

grid_multi = GridSearchCV(
    model,
    params2,
    cv=5,
    scoring='accuracy'
)

grid_multi.fit(x_train, y_train)

print(grid_multi.best_params_)
print(grid_multi.best_score_)
print(grid_multi.best_estimator_)

{'max_depth': 3, 'min_samples_leaf': 1, 'min_samples_split': 2}
0.8226315789473684
DecisionTreeClassifier(max_depth=3, random_state=42)

In [47]:
best_model2 = grid_multi.best_estimator_

train_pred2 = best_model2.predict(x_train)
test_pred2= best_model2.predict(x_test)

train_acc2 = accuracy_score(y_train, train_pred2)
test_acc2 = accuracy_score(y_test, test_pred2)

print(train_acc2)
print(test_acc2)

0.9479166666666666
0.8333333333333334

In [48]:
# 분류 모델 성적표
from sklearn.metrics import classification_report

print(classification_report(y_test, test_pred2))

              precision    recall  f1-score   support

           0       0.93      0.81      0.87        16
           1       0.70      0.88      0.78         8

    accuracy                           0.83        24
   macro avg       0.81      0.84      0.82        24
weighted avg       0.85      0.83      0.84        24

In [49]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, test_pred2)
cm

array([[13,  3],
       [ 1,  7]])

In [ ]:
grid_multi2 = GridSearchCV(
    model,
    params2,
    cv=5,
    scoring='recall' # recall 기준
)

grid_multi2.fit(x_train, y_train)

test_pred3 = grid_multi2.predict(x_test)

report = classification_report(y_test, test_pred3)
cm2 = confusion_matrix(y_test, test_pred3)

print(report)
print(cm2)

              precision    recall  f1-score   support

           0       0.87      0.81      0.84        16
           1       0.67      0.75      0.71         8

    accuracy                           0.79        24
   macro avg       0.77      0.78      0.77        24
weighted avg       0.80      0.79      0.79        24

[[13  3]
 [ 2  6]]

In [ ]:
print(grid_multi2.best_params_) # recall 기준 시 다른 모델을 고름
print(grid_multi2.best_score_)

{'max_depth': 5, 'min_samples_leaf': 2, 'min_samples_split': 10}
0.7857142857142857

In [54]:
# RandomizedSearchCV - 랜덤한 조합으로 검사
from sklearn.model_selection import RandomizedSearchCV

params_random = {
    'max_depth': [2, 3, 4, 5, 6, 7, 8, 9, 10],
    'min_samples_split': [2, 3, 4, 5, 6, 8, 10, 15],
    'min_samples_leaf': [1, 2, 3, 4, 5, 6, 8]
}

random_search = RandomizedSearchCV(
    model,
    params_random,
    n_iter=20,
    cv=5,
    scoring='accuracy',
    random_state=42
)

random_search.fit(x_train, y_train);

In [55]:
print(random_search.best_score_)
print(random_search.best_params_)
print(random_search.best_estimator_)

0.8226315789473684
{'min_samples_split': 6, 'min_samples_leaf': 2, 'max_depth': 4}
DecisionTreeClassifier(max_depth=4, min_samples_leaf=2, min_samples_split=6,
                       random_state=42)