In [10]:
import pandas as pd

df = pd.read_csv('aice_day2.csv')
df.head()

,customer_id,age,gender,membership,monthly_spend,visit_count,satisfaction,support_calls,region,churn
0,C001,27.0,Male,Standard,49.4,5,1.0,5,Seoul,Yes
1,C002,47.0,Male,Basic,46.2,17,5.0,0,Busan,No
2,C003,46.0,Male,Standard,53.4,1,2.0,5,Incheon,Yes
3,C004,37.0,Male,Basic,111.6,4,1.0,3,Seoul,Yes
4,C005,NaN,Female,Premium,107.6,18,1.0,3,Seoul,Yes

In [11]:
df['gender'] = df['gender'].map({
    'Male':0,
    'Female':1
})

In [43]:
df['gender'].value_counts()

gender
0    29
1    21
Name: count, dtype: int64

In [14]:
df['membership'].value_counts()

membership
Standard    22
Basic       20
Premium      8
Name: count, dtype: int64

In [15]:
pd.get_dummies(df['membership'])

    Basic  Premium  Standard
0   False    False      True
1    True    False     False
2   False    False      True
3    True    False     False
4   False     True     False
5   False    False      True
6    True    False     False
7   False    False      True
8   False    False      True
9    True    False     False
10   True    False     False
11   True    False     False
12  False    False      True
13  False    False      True
14   True    False     False
15   True    False     False
16  False     True     False
17  False    False      True
18  False    False      True
19  False    False      True
20  False    False      True
21   True    False     False
22   True    False     False
23   True    False     False
24  False    False      True
25  False     True     False
26  False     True     False
27   True    False     False
28  False    False      True
29  False    False      True
30  False    False      True
31   True    False     False
32   True    False     False
33   True    False     False
34  False     True     False
35  False    False      True
36  False     True     False
37  False    False      True
38  False    False      True
39  False    False      True
40  False     True     False
41   True    False     False
42   True    False     False
43  False    False      True
44   True    False     False
45   True    False     False
46  False     True     False
47   True    False     False
48  False    False      True
49  False    False      True

In [17]:
df = pd.get_dummies(df, columns=['membership'])

In [21]:
df.head()

,customer_id,age,gender,monthly_spend,visit_count,satisfaction,support_calls,region,churn,membership_Basic,membership_Premium,membership_Standard
0,C001,27.0,0,49.4,5,1.0,5,Seoul,Yes,False,False,True
1,C002,47.0,0,46.2,17,5.0,0,Busan,No,True,False,False
2,C003,46.0,0,53.4,1,2.0,5,Incheon,Yes,False,False,True
3,C004,37.0,0,111.6,4,1.0,3,Seoul,Yes,True,False,False
4,C005,NaN,1,107.6,18,1.0,3,Seoul,Yes,False,True,False

In [22]:
df['region'].isnull().sum()

np.int64(1)

In [23]:
df['region'].mode()[0]

'Seoul'

In [24]:
df['region'] = df['region'].fillna(df['region'].mode()[0])

In [26]:
df['region'].isnull().sum()

np.int64(0)

In [28]:
df = pd.get_dummies(df, columns=['region'])

In [29]:
df.head()

,customer_id,age,gender,monthly_spend,visit_count,satisfaction,support_calls,churn,membership_Basic,membership_Premium,membership_Standard,region_Busan,region_Daegu,region_Incheon,region_Seoul
0,C001,27.0,0,49.4,5,1.0,5,Yes,False,False,True,False,False,False,True
1,C002,47.0,0,46.2,17,5.0,0,No,True,False,False,True,False,False,False
2,C003,46.0,0,53.4,1,2.0,5,Yes,False,False,True,False,False,True,False
3,C004,37.0,0,111.6,4,1.0,3,Yes,True,False,False,False,False,False,True
4,C005,NaN,1,107.6,18,1.0,3,Yes,False,True,False,False,False,False,True

In [30]:
df.isnull().sum()

customer_id            0
age                    2
gender                 0
monthly_spend          2
visit_count            0
satisfaction           2
support_calls          0
churn                  0
membership_Basic       0
membership_Premium     0
membership_Standard    0
region_Busan           0
region_Daegu           0
region_Incheon         0
region_Seoul           0
dtype: int64

In [31]:
df.describe()

,age,gender,monthly_spend,visit_count,satisfaction,support_calls
count,48.000000,50.000000,48.000000,50.00000,48.000000,50.000000
mean,38.625000,0.420000,77.554167,9.80000,2.937500,2.440000
std,11.430875,0.498569,36.682206,5.57692,1.493336,1.864381
min,21.000000,0.000000,20.400000,1.00000,1.000000,0.000000
25%,28.500000,0.000000,45.300000,4.25000,2.000000,1.000000
50%,38.000000,0.000000,81.200000,10.00000,2.000000,2.000000
75%,47.250000,1.000000,108.575000,14.00000,5.000000,4.750000
max,59.000000,1.000000,133.100000,18.00000,5.000000,5.000000

In [33]:
df['age'] = df['age'].fillna(df['age'].median())

In [34]:
df['monthly_spend'] = df['monthly_spend'].fillna(df['monthly_spend'].median())

In [35]:
df['satisfaction'] = df['satisfaction'].fillna(df['satisfaction'].median())

In [36]:
df.describe()

,age,gender,monthly_spend,visit_count,satisfaction,support_calls
count,50.000000,50.000000,50.000000,50.00000,50.000000,50.000000
mean,38.600000,0.420000,77.700000,9.80000,2.900000,2.440000
std,11.195845,0.498569,35.933039,5.57692,1.474269,1.864381
min,21.000000,0.000000,20.400000,1.00000,1.000000,0.000000
25%,29.250000,0.000000,45.750000,4.25000,2.000000,1.000000
50%,38.000000,0.000000,81.200000,10.00000,2.000000,2.000000
75%,47.000000,1.000000,107.550000,14.00000,4.750000,4.750000
max,59.000000,1.000000,133.100000,18.00000,5.000000,5.000000

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          50 non-null     str
 1   age                  50 non-null     float64
 2   gender               50 non-null     int64
 3   monthly_spend        50 non-null     float64
 4   visit_count          50 non-null     int64
 5   satisfaction         50 non-null     float64
 6   support_calls        50 non-null     int64
 7   churn                50 non-null     str
 8   membership_Basic     50 non-null     bool
 9   membership_Premium   50 non-null     bool
 10  membership_Standard  50 non-null     bool
 11  region_Busan         50 non-null     bool
 12  region_Daegu         50 non-null     bool
 13  region_Incheon       50 non-null     bool
 14  region_Seoul         50 non-null     bool
dtypes: bool(7), float64(3), int64(3), str(2)
memory usage: 3.6 KB

In [38]:
df.isnull().sum()

customer_id            0
age                    0
gender                 0
monthly_spend          0
visit_count            0
satisfaction           0
support_calls          0
churn                  0
membership_Basic       0
membership_Premium     0
membership_Standard    0
region_Busan           0
region_Daegu           0
region_Incheon         0
region_Seoul           0
dtype: int64

In [39]:
df.dtypes

customer_id                str
age                    float64
gender                   int64
monthly_spend          float64
visit_count              int64
satisfaction           float64
support_calls            int64
churn                      str
membership_Basic          bool
membership_Premium        bool
membership_Standard       bool
region_Busan              bool
region_Daegu              bool
region_Incheon            bool
region_Seoul              bool
dtype: object

In [40]:
df['churn'] = df['churn'].map({
    'No': 0,
    'Yes':1
})

In [41]:
df['churn']

0     1
1     0
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    0
11    0
12    1
13    0
14    0
15    0
16    0
17    1
18    0
19    1
20    1
21    1
22    0
23    1
24    0
25    0
26    0
27    1
28    0
29    0
30    0
31    0
32    1
33    1
34    1
35    0
36    0
37    0
38    0
39    0
40    0
41    1
42    0
43    0
44    0
45    1
46    1
47    1
48    0
49    0
Name: churn, dtype: int64

In [44]:
x = df.drop(columns=['customer_id','churn'])

In [45]:
x.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  50 non-null     float64
 1   gender               50 non-null     int64
 2   monthly_spend        50 non-null     float64
 3   visit_count          50 non-null     int64
 4   satisfaction         50 non-null     float64
 5   support_calls        50 non-null     int64
 6   membership_Basic     50 non-null     bool
 7   membership_Premium   50 non-null     bool
 8   membership_Standard  50 non-null     bool
 9   region_Busan         50 non-null     bool
 10  region_Daegu         50 non-null     bool
 11  region_Incheon       50 non-null     bool
 12  region_Seoul         50 non-null     bool
dtypes: bool(7), float64(3), int64(3)
memory usage: 2.8 KB

In [46]:
y = df['churn']

In [47]:
y.info()

<class 'pandas.Series'>
RangeIndex: 50 entries, 0 to 49
Series name: churn
Non-Null Count  Dtype
--------------  -----
50 non-null     int64
dtypes: int64(1)
memory usage: 532.0 bytes

In [48]:
x.head()

,age,gender,monthly_spend,visit_count,satisfaction,support_calls,membership_Basic,membership_Premium,membership_Standard,region_Busan,region_Daegu,region_Incheon,region_Seoul
0,27.0,0,49.4,5,1.0,5,False,False,True,False,False,False,True
1,47.0,0,46.2,17,5.0,0,True,False,False,True,False,False,False
2,46.0,0,53.4,1,2.0,5,False,False,True,False,False,True,False
3,37.0,0,111.6,4,1.0,3,True,False,False,False,False,False,True
4,38.0,1,107.6,18,1.0,3,False,True,False,False,False,False,True

In [49]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: churn, dtype: int64

In [50]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [51]:
x_train.shape

(40, 13)

In [53]:
x_test.shape

(10, 13)

In [54]:
y_train.shape

(40,)

In [55]:
y_test.shape

(10,)

In [56]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [57]:
y.value_counts()

churn
0    27
1    23
Name: count, dtype: int64

In [58]:
y_train.value_counts()

churn
0    22
1    18
Name: count, dtype: int64

In [59]:
y_test.value_counts()

churn
0    5
1    5
Name: count, dtype: int64

In [60]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(
    random_state=42
)

In [63]:
model.fit(x_train, y_train);

In [64]:
pred = model.predict(x_test)
pred

array([1, 1, 0, 0, 1, 0, 1, 1, 1, 0])

In [66]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, pred)
accuracy

0.5

In [67]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, pred)
cm

array([[2, 3],
       [2, 3]])

In [68]:
from sklearn.metrics import precision_score, recall_score

precision = precision_score(y_test, pred)
recall = recall_score(y_test, pred)

precision, recall

(0.5, 0.6)

In [69]:
from sklearn.metrics import f1_score

f1 = f1_score(y_test, pred)
f1

0.5454545454545454